import { ComponentTypes, Inspection } from './types';

export const formFixture: Inspection = {
  name: 'Default Monthly Inspection',
  uuid: '08eed68b-c7c9-4a33-9297-dc6aafbfedb4',
  systemName: 'default_monthly_inspection_dc6aafbfedb4',
  parentFormUUID: '00000000-0000-0000-0000-000000000000',
  version: '1.0.0',
  order: 0,
  formGroups: [
    {
      name: 'Pre Step',
      isHidden: false,
      uuid: 'f8dbeab4-1b67-43e0-9719-b9ff461739d2',
      systemName: '',
      parentFormUUID: '',
      version: '',
      order: 0,
      formFields: [
        {
          uuid: '1d88c6ca-7f83-4ccc-8562-461b86f5ca4f',
          defaultValue: 'no helper text needed',
          helperText: 'no helper text needed',
          isRequired: false,
          kind: ComponentTypes.NUMBER,
          label: 'Odometer',
          placeholderValue: '',
          inputValue: '',
          order: 1,
          formFieldOptions: [],
        },
        {
          uuid: '937b23e4-6933-4cd4-b215-2b3e428c2324',
          defaultValue: 'no helper text needed',
          helperText: 'no helper text needed',
          isRequired: true,
          kind: ComponentTypes.SINGLE_IMAGE,
          label: 'Odometer Picture',
          placeholderValue: '',
          inputValue: '',
          order: 2,
          formFieldOptions: [],
        },
      ],
    },
    {
      name: 'Quick Walkaround',
      isHidden: false,
      uuid: 'eb7e38ff-1016-402c-a4e7-7440319227af',
      systemName: 'default_monthly_inspection_dc6aafbfedb4_quick_walkaround',
      parentFormUUID: '08eed68b-c7c9-4a33-9297-dc6aafbfedb4',
      version: '1.0.0',
      order: 0,
      formFields: [
        {
          uuid: 'bc5e8e27-ba02-4563-8697-44b57980ff83',
          defaultValue: '',
          helperText:
            'Walk around the vehicle with voiceover to display the overall health of the vehicle, recording any damages. ',
          isRequired: true,
          kind: ComponentTypes.VIDEO,
          label: 'Walk-around Video',
          placeholderValue: '',
          inputValue: '',
          order: 0,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: '',
              value: '',
              uuid: '92928b1e-1d53-4243-b305-1c2ff6b56c55',
              order: 0,
            },
          ],
        },
        {
          uuid: '1d693d34-46af-4a1e-a582-ef26477b089d',
          defaultValue: '',
          helperText:
            'You will have a chance to report tire damage, window condition, light damage, etc in the next steps. This is only for body damage. ',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Is there any exterior body damage?',
          placeholderValue: '',
          inputValue: '',
          order: 1,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Body damage present',
              value: 'body_damage_present',
              uuid: 'debf0e8e-3929-4786-91be-d6ecddad0cb2',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'No body damage found',
              value: 'no_body_damage_found',
              uuid: '12182eab-23ac-41b5-b4b3-ceb74574caaa',
              order: 1,
            },
          ],
        },
        {
          uuid: 'faf3246c-a1bd-4a59-b277-7435a6169174',
          defaultValue: '',
          helperText: '',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'What is the exterior cleanliness level? ',
          placeholderValue: '',
          inputValue: '',
          order: 2,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Clean',
              value: 'clean',
              uuid: '8021957b-324d-48e3-bed8-116c38fb5cc9',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'L2 - Slightly dirty',
              value: 'l2_-_slightly_dirty',
              uuid: 'a32a65ee-27ad-497b-be8b-dbf3ad695235',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'L3 - Needs wash',
              value: 'l3_-_needs_wash',
              uuid: '1732133a-77bd-4ed8-b6bd-4251382bd75f',
              order: 2,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'L4 - Vandalized',
              value: 'l4_-_vandalized',
              uuid: 'e2bc1f5b-48e0-44d4-bf33-21b5edf24687',
              order: 3,
            },
          ],
        },
      ],
    },
    {
      name: 'Paperwork',
      isHidden: false,
      uuid: 'ec2efbd8-c654-4ec5-b327-69322be17881',
      systemName: 'default_monthly_inspection_dc6aafbfedb4_paperwork',
      parentFormUUID: '08eed68b-c7c9-4a33-9297-dc6aafbfedb4',
      version: '1.0.0',
      order: 1,
      formFields: [
        {
          uuid: '324dc1bb-1171-413d-9375-86fd172d6cf2',
          defaultValue: '',
          helperText: 'Document whether the insurance is up to date.',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Is Insurance Current?',
          placeholderValue: '',
          inputValue: '',
          order: 0,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Up to date',
              value: 'up_to_date',
              uuid: 'a25a7c35-3acf-4960-acb2-a99b6b14af94',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Expired',
              value: 'expired',
              uuid: '996cbc26-4f47-4a9e-a1e0-a4120809b5cc',
              order: 1,
            },
          ],
        },
        {
          uuid: 'c05dfda4-f179-430b-b0c9-fcb023234e2e',
          defaultValue: '',
          helperText: 'Check to make sure the registration is current.',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Is registration current? ',
          placeholderValue: '',
          inputValue: '',
          order: 1,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Up to date',
              value: 'up_to_date',
              uuid: '3222cfb8-0f42-4b5d-a07f-095470f7b93e',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Expired',
              value: 'expired',
              uuid: '1f849e10-ea46-4dc4-98e8-532742596d6b',
              order: 1,
            },
          ],
        },
        {
          uuid: 'c546a96c-d65b-43e8-955a-0d7f89dae0ee',
          defaultValue: '',
          helperText: 'Take a photo of the registration',
          isRequired: true,
          kind: ComponentTypes.SINGLE_IMAGE,
          label: 'Registration Photo',
          placeholderValue: '',
          inputValue: '',
          order: 2,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: '',
              value: '',
              uuid: '59f7a9b9-21cf-43a9-9771-1f3c5ca5d4a7',
              order: 0,
            },
          ],
        },
      ],
    },
    {
      name: 'Interior',
      isHidden: false,
      uuid: '3d11837b-171d-49da-85b5-54614376c602',
      systemName: 'default_monthly_inspection_dc6aafbfedb4_interior',
      parentFormUUID: '08eed68b-c7c9-4a33-9297-dc6aafbfedb4',
      version: '1.0.0',
      order: 2,
      formFields: [
        {
          uuid: '8a916e26-6695-4b01-94d2-773f840cb7c0',
          defaultValue: '',
          helperText:
            'Specify the interior cleanliness of the vehicle. This question does NOT include logging the smell of smoke. ',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'What is the interior cleanliness level?',
          placeholderValue: '',
          inputValue: '',
          order: 0,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Clean',
              value: 'clean',
              uuid: '997e929e-97b4-4d5f-99cb-1e38298d61f7',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'L1 - Little dirty needs wipe down',
              value: 'l1_-_little_dirty_needs_wipe_down',
              uuid: 'e76808e2-b894-4fcb-a139-dcf30c772c37',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'L2 - Dirty with trash and smell',
              value: 'l2_-_dirty_with_trash_and_smell',
              uuid: 'cd9aad71-bb54-4225-aa07-a23ce1d8b1cd',
              order: 2,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'L3 - Very dirty and trashed',
              value: 'l3_-_very_dirty_and_trashed',
              uuid: '6fab8821-3502-4c7c-9a29-2d6c03d28ec1',
              order: 3,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'L4 - Extremely toxic',
              value: 'l4_-_extremely_toxic',
              uuid: '319d3e0b-04ed-4ff7-8a7c-e0d404bc0410',
              order: 4,
            },
          ],
        },
        {
          uuid: '02a605b4-c89d-4616-92db-abb18171d60f',
          defaultValue: '',
          helperText: 'Document if there is any new interior damage',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Is there any interior damage?',
          placeholderValue: '',
          inputValue: '',
          order: 1,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'No new damage',
              value: 'no_new_damage',
              uuid: 'bf47fb13-db59-48c7-8d4d-88cb52c1c30c',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'New damage found',
              value: 'new_damage_found',
              uuid: '2881a41c-fbf2-4cea-a74b-7eabf364a5f6',
              order: 1,
            },
          ],
        },
        {
          uuid: '1c2e692e-3d24-4cc3-a856-33b375725750',
          defaultValue: '',
          helperText:
            'Record any engine light message present. If none exists, you may skip this step and leave it blank. ',
          isRequired: false,
          kind: ComponentTypes.TEXTAREA,
          label: 'Record any engine light message',
          placeholderValue: '',
          inputValue: '',
          order: 2,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: '',
              value: '',
              uuid: '9679bb4a-0686-4986-8d08-efbb56863c70',
              order: 0,
            },
          ],
        },
        {
          uuid: 'cb3ef01a-c50a-46a8-ab0e-5421ec16e3cd',
          defaultValue: '',
          helperText: 'Check if all the cab lights are functional.',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Are all cab lights functioning?',
          placeholderValue: '',
          inputValue: '',
          order: 3,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'All cab lights working',
              value: 'all_cab_lights_working',
              uuid: 'dae8ebac-3a48-4c77-ab9f-fc5230d8710d',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Cab lights need replacing',
              value: 'cab_lights_need_replacing',
              uuid: '0170e8ab-cd86-47c8-acb7-45f9ee92572c',
              order: 1,
            },
          ],
        },
        {
          uuid: 'b611acfd-0c7a-4194-be1a-4f2d17cc10e8',
          defaultValue: '',
          helperText:
            'Enter the last 4 digits of the toll transponder, or skip if there is no transponder installed',
          isRequired: false,
          kind: ComponentTypes.TEXT,
          label: 'Last 4 of toll transponder',
          placeholderValue: '',
          inputValue: '',
          order: 4,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: '',
              value: '',
              uuid: '15c7afae-190d-4245-814f-ab0f34ab2171',
              order: 0,
            },
          ],
        },
        {
          uuid: '98c7b705-3e3e-4633-91c9-9c673c116a47',
          defaultValue: '',
          helperText: 'Take a photo of the toll transponder, or skip if there is none present',
          isRequired: false,
          kind: ComponentTypes.SINGLE_IMAGE,
          label: 'Take photo of toll transponder',
          placeholderValue: '',
          inputValue: '',
          order: 5,
          formFieldOptions: [],
        },
        {
          uuid: '772c3db0-7aeb-446e-9729-fecb23bb3ee1',
          defaultValue: '',
          helperText:
            'Input the mileage value of the oil change sticker, or skip if a sticker is not present',
          isRequired: false,
          kind: ComponentTypes.NUMBER,
          label: 'Oil change sticker mileage',
          placeholderValue: '',
          inputValue: '',
          order: 6,
          formFieldOptions: [],
        },
        {
          uuid: '7763a0da-cf8a-4a9f-bce8-46fc3a42e71e',
          defaultValue: '',
          helperText: 'If there is no backup camera, select yes. ',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Is the backup camera functional? ',
          placeholderValue: '',
          inputValue: '',
          order: 7,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Functioning properly',
              value: 'functioning_properly',
              uuid: 'd6afa466-8ffb-454c-8e6d-c2918db5ee09',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Not functioning properly',
              value: 'not_functioning_properly',
              uuid: 'e93fd180-0a77-41d9-a50b-e606517154c2',
              order: 1,
            },
          ],
        },
        {
          uuid: '39f43fce-9e93-4f90-812f-bc2cd7912ec8',
          defaultValue: '',
          helperText: 'Check the health of the rear view mirror. ',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Is rear view mirror ok? ',
          placeholderValue: '',
          inputValue: '',
          order: 8,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Mirror is ok',
              value: 'mirror_is_ok',
              uuid: '87876637-9f13-41f4-865d-474fb6053a3a',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Mirror is broken/not ok',
              value: 'mirror_is_broken/not_ok',
              uuid: '8145c421-c4f0-46ff-8f74-2c51a30d3d8c',
              order: 1,
            },
          ],
        },
        {
          uuid: '94682a31-6c0c-40e7-9bdf-80f4084c3497',
          defaultValue: '',
          helperText: 'Check the health of the driver side mirror',
          isRequired: false,
          kind: ComponentTypes.RADIO,
          label: 'Is driver side mirror ok? ',
          placeholderValue: '',
          inputValue: '',
          order: 9,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Mirror ok',
              value: 'mirror_ok',
              uuid: '3a6736a7-553e-49d5-863b-5c85184c5fe1',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Mirror broken / not ok',
              value: 'mirror_broken_/_not_ok',
              uuid: '58359527-649e-4a48-9d96-24ef830b43c1',
              order: 1,
            },
          ],
        },
        {
          uuid: 'd4b37ba5-2377-448e-8743-e115a0840c19',
          defaultValue: '',
          helperText: 'Check the health of the passenger side mirror',
          isRequired: true,
          kind: ComponentTypes.MULTISELECT,
          label: 'Is passenger side mirror ok?',
          placeholderValue: '',
          inputValue: '',
          order: 10,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: true,
              label: 'Mirror ok',
              value: 'mirror_ok',
              uuid: '94f8d9ba-b535-49a3-a674-0d8ea08dff37',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Mirror broken / not ok',
              value: 'mirror_broken_/_not_ok',
              uuid: '6a965173-a4e5-402d-a67a-72f9f9f0d531',
              order: 1,
            },
          ],
        },
        {
          uuid: '4ce3615d-f021-4601-be4e-cbf6859140c3',
          defaultValue: '',
          helperText: 'Test the AC and heat. ',
          isRequired: true,
          kind: ComponentTypes.MULTISELECT,
          label: 'Does climate control work?',
          placeholderValue: '',
          inputValue: '',
          order: 11,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Everything works',
              value: 'everything_works',
              uuid: 'ea991fc9-22a1-4db6-bde1-374079d333e5',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Problem with AC',
              value: 'problem_with_ac',
              uuid: 'ba6a6757-e838-457f-8432-4cb59fa980a6',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Problem with heat',
              value: 'problem_with_heat',
              uuid: '6e5cd92a-cc6d-460d-b437-90d203e85f90',
              order: 2,
            },
          ],
        },
        {
          uuid: '012e165d-80f3-4c8c-ac4c-e4f0bb30a938',
          defaultValue: '',
          helperText: 'Check to make sure all windows roll up. ',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Do all windows roll up?',
          placeholderValue: '',
          inputValue: '',
          order: 12,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'All windows roll up',
              value: 'all_windows_roll_up',
              uuid: 'a1ae5193-1371-4897-970d-ea6e46184ba2',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'One/some windows do not roll up',
              value: 'one/some_windows_do_not_roll_up',
              uuid: '6d2a88a9-5f44-4ddd-86dc-a1f4be529640',
              order: 1,
            },
          ],
        },
        {
          uuid: '94f4efaa-f8cc-4024-8590-3226dd3943fa',
          defaultValue: '',
          helperText: 'Check to make sure the horn makes noise.',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Does the horn work? ',
          placeholderValue: '',
          inputValue: '',
          order: 13,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Horn works',
              value: 'horn_works',
              uuid: 'cb034840-3150-4653-88b0-d6fea8e04848',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Horn does not work',
              value: 'horn_does_not_work',
              uuid: '153ede45-0ac9-44b7-9364-929d42678b35',
              order: 1,
            },
          ],
        },
      ],
    },
    {
      name: 'Lights',
      isHidden: false,
      uuid: 'e1c0a1ff-77c1-4925-83da-b1ad9a5d4a5f',
      systemName: 'default_monthly_inspection_dc6aafbfedb4_lights',
      parentFormUUID: '08eed68b-c7c9-4a33-9297-dc6aafbfedb4',
      version: '1.0.0',
      order: 3,
      formFields: [
        {
          uuid: 'cdaff9d6-d12b-429d-9581-6f829e82fb67',
          defaultValue: '',
          helperText: 'Check all 4 blinker lights, front and back',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Are all blinker lights functioning? ',
          placeholderValue: '',
          inputValue: '',
          order: 0,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'All lights functioning',
              value: 'all_lights_functioning',
              uuid: 'aa43ad6e-7195-4b79-acea-e38a843fa068',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'One/some lights not functioning',
              value: 'one/some_lights_not_functioning',
              uuid: '3e05ff1d-001b-4d9d-a21a-b05737024b44',
              order: 1,
            },
          ],
        },
        {
          uuid: '8a71ab2a-b0f6-4813-bdfe-08f848a9ec71',
          defaultValue: '',
          helperText:
            'Check that all marker lights are functioning. Marker lights are the ones on the top of the cargo cans.',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Are all marker lights functioning? ',
          placeholderValue: '',
          inputValue: '',
          order: 1,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'All lights functioning',
              value: 'all_lights_functioning',
              uuid: '363723c7-09aa-49ed-8cee-d6870f5d1f9a',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'One/some lights not functioning',
              value: 'one/some_lights_not_functioning',
              uuid: '5d9a16f6-cdb5-4692-acf9-4f711fe5055d',
              order: 1,
            },
          ],
        },
        {
          uuid: '5d025501-3bc4-4b5f-9201-70f40fb14911',
          defaultValue: '',
          helperText:
            'Check to make sure all license plate lights are functioning, back and front (if applicable)',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Are all license plate lights functioning',
          placeholderValue: '',
          inputValue: '',
          order: 2,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'All lights functioning',
              value: 'all_lights_functioning',
              uuid: 'ecebda93-7c5b-4dd9-b5c9-50dd6d96693c',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Some lights not functioning',
              value: 'some_lights_not_functioning',
              uuid: '4ffbd879-031b-4128-a813-5689a07015e0',
              order: 1,
            },
          ],
        },
        {
          uuid: 'c07f04fb-7455-491e-9fd1-524e0e1fc94f',
          defaultValue: '',
          helperText: 'Check to make sure low beams are functioning',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Are low beams functioning?',
          placeholderValue: '',
          inputValue: '',
          order: 3,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Functional',
              value: 'functional',
              uuid: '394d4a9f-dcbc-4034-81f0-3448f0fec36b',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Not functional',
              value: 'not_functional',
              uuid: 'ef70085c-55f2-4083-a958-afd3ee2ce62c',
              order: 1,
            },
          ],
        },
        {
          uuid: 'a461bcb7-2c0a-4069-abab-8b58d8281c3d',
          defaultValue: '',
          helperText: 'Check to make sure both high beams are working',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Are high beams functioning',
          placeholderValue: '',
          inputValue: '',
          order: 4,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'High beams good',
              value: 'high_beams_good',
              uuid: '05780244-6b28-4467-8f88-a85b6e0ad745',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'High beams not working',
              value: 'high_beams_not_working',
              uuid: 'c5da92f1-20f6-4bfb-82e6-0b2f5b04bc48',
              order: 1,
            },
          ],
        },
        {
          uuid: '3ef27e8a-2829-4d15-af0a-bbae310babc4',
          defaultValue: '',
          helperText: 'Check to make sure both brake lights are functional with foot on the brake',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Are the brake lights functional?',
          placeholderValue: '',
          inputValue: '',
          order: 5,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Brake lights good',
              value: 'brake_lights_good',
              uuid: '521b1eca-1d35-41ec-951a-9e9451dfceea',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Brake light(s) not working',
              value: 'brake_light(s)_not_working',
              uuid: '1a50d716-7ba0-4556-9bdc-b692613ffd78',
              order: 1,
            },
          ],
        },
      ],
    },
    {
      name: 'Under the hood',
      isHidden: false,
      uuid: '19803042-4877-420b-a2f9-fc0e581dd014',
      systemName: 'default_monthly_inspection_dc6aafbfedb4_under_the_hood',
      parentFormUUID: '08eed68b-c7c9-4a33-9297-dc6aafbfedb4',
      version: '1.0.0',
      order: 4,
      formFields: [
        {
          uuid: 'fec7a1c8-b4e3-4618-946b-cfed65d8bdd8',
          defaultValue: '',
          helperText: 'Check to make sure wiper fluid is topped off and fill if necessary. ',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Top off wiper fluid',
          placeholderValue: '',
          inputValue: '',
          order: 0,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Already full',
              value: 'already_full',
              uuid: 'e35476d7-5f3a-4cf8-a4f6-018a839bce63',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Needed top off',
              value: 'needed_top_off',
              uuid: '4050f494-1dd5-4153-a976-da82f44271d3',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Was empty',
              value: 'was_empty',
              uuid: '20d5ecd0-d88d-4e29-90e9-a78450355415',
              order: 2,
            },
          ],
        },
        {
          uuid: '9adfb443-0a1c-46fb-9110-70098bd2d1e8',
          defaultValue: '',
          helperText: 'Check the coolant level and fill if necessary',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Check coolant level',
          placeholderValue: '',
          inputValue: '',
          order: 1,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Level is healthy',
              value: 'level_is_healthy',
              uuid: '075903cb-7382-4297-ac2a-29b269b33a94',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Needed filling',
              value: 'needed_filling',
              uuid: '1a850b70-0c00-49e9-91ad-87b9f0a25e38',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Was very low or empty',
              value: 'was_very_low_or_empty',
              uuid: 'e71f0886-cf5a-456e-863c-7ed207c894f7',
              order: 2,
            },
          ],
        },
        {
          uuid: '931b073a-2320-4ee5-94a5-d9613539257b',
          defaultValue: '',
          helperText: 'Check the oil level and fill if necessary',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Check / fill oil level',
          placeholderValue: '',
          inputValue: '',
          order: 2,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Oil level healthy',
              value: 'oil_level_healthy',
              uuid: 'eca37401-c85b-499f-86fc-ca3bf24c1641',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Needed filling',
              value: 'needed_filling',
              uuid: '7cb0193e-e62d-43ae-a49b-c425d5922be7',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Needed filling - very low',
              value: 'needed_filling_-_very_low',
              uuid: '43d405c9-b563-46d1-b1c6-865d1a167358',
              order: 2,
            },
          ],
        },
        {
          uuid: 'b2b09b22-3c31-44ea-bc49-6c2d4b1a9f16',
          defaultValue: '',
          helperText: 'Check the level of the power steering fluid and fill if necessary',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Check / fill power steering fluid',
          placeholderValue: '',
          inputValue: '',
          order: 3,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Steering fluid level healthy',
              value: 'steering_fluid_level_healthy',
              uuid: 'e92375c3-b30c-4fb8-b382-c0020b8b4721',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Needed fill',
              value: 'needed_fill',
              uuid: 'de906eee-2290-4955-b560-161f0b6dede5',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Very low / empty',
              value: 'very_low_/_empty',
              uuid: '3f7378d2-2069-48f2-b370-af44ddbda7d8',
              order: 2,
            },
          ],
        },
        {
          uuid: '8cb7d71d-2918-493d-87ed-0769b621f3eb',
          defaultValue: '',
          helperText: 'Check the level of the brake fluid, and fill if necessary',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Check / fill brake fluid',
          placeholderValue: '',
          inputValue: '',
          order: 4,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Brake fluid level healthy',
              value: 'brake_fluid_level_healthy',
              uuid: '2d5f9dd8-266c-40be-ba0c-3daf92ca0b4c',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Needed filling',
              value: 'needed_filling',
              uuid: '046e9523-0419-43c0-890d-79b8962b2fce',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Very low / empty',
              value: 'very_low_/_empty',
              uuid: '70644514-97e4-4e3a-a8c3-81aafa75e061',
              order: 2,
            },
          ],
        },
        {
          uuid: '459b808b-f453-40e5-9c47-407e0059e389',
          defaultValue: '',
          helperText: 'Check the health of the serpentine belt. ',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Check health of serpentine belt',
          placeholderValue: '',
          inputValue: '',
          order: 5,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Belt looks good',
              value: 'belt_looks_good',
              uuid: 'fb043cf8-8e35-4995-b348-1693f6577b72',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Belt needs replacing ',
              value: 'belt_needs_replacing_',
              uuid: '823658b6-d143-4640-9d16-79132c2434f2',
              order: 1,
            },
          ],
        },
      ],
    },
    {
      name: 'Front',
      isHidden: false,
      uuid: '6d84820d-1457-4c62-a20c-b1146b057255',
      systemName: 'default_monthly_inspection_dc6aafbfedb4_vehicle_front',
      parentFormUUID: '08eed68b-c7c9-4a33-9297-dc6aafbfedb4',
      version: '1.0.0',
      order: 5,
      formFields: [
        {
          uuid: '79291d5d-e05e-4dfb-9769-b4b1d7a21a94',
          defaultValue: '',
          helperText:
            'Document the condition of the front plate. Select N/A if your state does not require front plates',
          isRequired: false,
          kind: ComponentTypes.RADIO,
          label: 'Front plate condition',
          placeholderValue: '',
          inputValue: '',
          order: 0,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'N/A',
              value: 'n/a',
              uuid: 'f3393011-81e2-4695-8524-74053b3d2501',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Good condition',
              value: 'good_condition',
              uuid: '13bd6598-f21c-41af-9f39-fd47f0963b52',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Damaged plate ',
              value: 'damaged_plate_',
              uuid: '2d3907f2-0ab2-492e-bae0-bc4d639a8320',
              order: 2,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Missing plate',
              value: 'missing_plate',
              uuid: '5cb7f1d7-4c2a-4e1e-a59a-17d7660a83aa',
              order: 3,
            },
          ],
        },
        {
          uuid: '54965783-94ad-497d-b54d-2b5fe0f4c60f',
          defaultValue: '',
          helperText:
            'Take a picture of the front plate or skip if your state does not require a front plate',
          isRequired: false,
          kind: ComponentTypes.SINGLE_IMAGE,
          label: 'Picture of front plate',
          placeholderValue: '',
          inputValue: '',
          order: 1,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: '',
              value: '',
              uuid: 'dc4255f7-035b-4c82-bee9-3d872702ce01',
              order: 0,
            },
          ],
        },
        {
          uuid: 'e55a96ba-0694-4c9e-9543-aa5eee98cc13',
          defaultValue: '',
          helperText: 'Note the condition of the windshield. ',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Windshield condition',
          placeholderValue: '',
          inputValue: '',
          order: 2,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Good condition',
              value: 'good_condition',
              uuid: '32411060-b454-40b7-90c4-9f875169c19c',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Cracked',
              value: 'cracked',
              uuid: '53246149-5da4-4d92-9986-f13f8724f688',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Chipped',
              value: 'chipped',
              uuid: '6d5e2560-0158-4466-805f-0cd9c6d7740a',
              order: 2,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Shattered - Should not be driven',
              value: 'shattered_-_should_not_be_driven',
              uuid: 'd97be75d-8e3b-450c-9a67-22b5648cc47a',
              order: 3,
            },
          ],
        },
        {
          uuid: 'f0588ba7-f86d-4ec4-b545-5d168f839495',
          defaultValue: '',
          helperText: 'Document the condition of the windshield wipers. Replace wipers if needed. ',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Wiper condition',
          placeholderValue: '',
          inputValue: '',
          order: 3,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Wipers ok',
              value: 'wipers_ok',
              uuid: 'ae02f54d-308c-4208-879b-f37db1e41101',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Wiper(s) needed replacement',
              value: 'wiper(s)_needed_replacement',
              uuid: 'eb0681c2-bc0e-475f-aaac-8c60c82331f3',
              order: 1,
            },
          ],
        },
      ],
    },
    {
      name: 'Driver Side Front',
      isHidden: false,
      uuid: '13edd867-d8bb-4cad-93b5-5f0d188ab834',
      systemName: 'default_monthly_inspection_dc6aafbfedb4_driver_side_front',
      parentFormUUID: '08eed68b-c7c9-4a33-9297-dc6aafbfedb4',
      version: '1.0.0',
      order: 6,
      formFields: [
        {
          uuid: '4a233a95-ad07-4286-9027-1bc8635d908b',
          defaultValue: '',
          helperText: 'Inspect the driver door check',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Driver Door Check',
          placeholderValue: '',
          inputValue: '',
          order: 0,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Door check ok',
              value: 'door_check_ok',
              uuid: '343af71d-ed20-4d9f-9272-0f437187e7a2',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Door check issue',
              value: 'door_check_issue',
              uuid: '477e559c-548f-496e-9d01-5bafa0303734',
              order: 1,
            },
          ],
        },
        {
          uuid: 'b2cc4377-aa7b-4494-b457-eb1ab129b7ed',
          defaultValue: '',
          helperText: 'Inspect the door hinge for damage. ',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Door hinge check',
          placeholderValue: '',
          inputValue: '',
          order: 1,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Door hinge ok',
              value: 'door_hinge_ok',
              uuid: 'f51ff5fe-3a3a-4aaa-8a14-411772ee56ad',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Door hinge damaged',
              value: 'door_hinge_damaged',
              uuid: '1ef41cca-28fd-47d7-9bbd-dbcb17ae8d5f',
              order: 1,
            },
          ],
        },
        {
          uuid: 'a34e8511-0d7c-4505-b2b2-d3a3aad471b4',
          defaultValue: '',
          helperText: 'Check the condition of the door window',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Door window condition',
          placeholderValue: '',
          inputValue: '',
          order: 2,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Window ok',
              value: 'window_ok',
              uuid: 'f3dd6cec-0c7b-4a0a-92aa-081e7d88d5e0',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Cracked',
              value: 'cracked',
              uuid: 'de401527-84b6-4ed1-9ce2-66877fc359e4',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Chipped',
              value: 'chipped',
              uuid: '4b3ab4de-ab96-41bd-ae47-f0b5158be747',
              order: 2,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Shattered',
              value: 'shattered',
              uuid: '25dc991b-a0d4-4b54-bdf0-946af7fce7c4',
              order: 3,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Other damage',
              value: 'other_damage',
              uuid: 'cd40f78d-d0ff-494c-9cb7-b4567bcf9840',
              order: 4,
            },
          ],
        },
        {
          uuid: '2903218d-d304-4dae-b3a7-8dc6feec958e',
          defaultValue: '',
          helperText: 'Check the tread level of the inner tire',
          isRequired: true,
          kind: ComponentTypes.NUMBER,
          label: 'Inner tread level',
          placeholderValue: '',
          inputValue: '',
          order: 3,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: '',
              value: '',
              uuid: 'e154e02e-be6a-4903-a64d-933168cf5ad9',
              order: 0,
            },
          ],
        },
        {
          uuid: '08fffb41-9b28-4215-b539-64a9b2de32a8',
          defaultValue: '',
          helperText: 'Check the level of the middle tread',
          isRequired: true,
          kind: ComponentTypes.NUMBER,
          label: 'Middle tread level',
          placeholderValue: '',
          inputValue: '',
          order: 4,
          formFieldOptions: [],
        },
        {
          uuid: '6a62ca10-207c-4f78-a677-743f26060736',
          defaultValue: '',
          helperText: 'Check the level of the outer tread',
          isRequired: true,
          kind: ComponentTypes.NUMBER,
          label: 'Outer tread level',
          placeholderValue: '',
          inputValue: '',
          order: 5,
          formFieldOptions: [],
        },
        {
          uuid: 'df8082a3-07b6-4c86-975a-6bed1d33cbc5',
          defaultValue: '',
          helperText: 'Take a picture of the tire tread',
          isRequired: true,
          kind: ComponentTypes.SINGLE_IMAGE,
          label: 'Tread Picture',
          placeholderValue: '',
          inputValue: '',
          order: 6,
          formFieldOptions: [],
        },
        {
          uuid: 'e9090d5b-c807-42cb-b623-9b687cb30989',
          defaultValue: '',
          helperText:
            'Record if the tire pressure is ok for the vehicle and fill the tire up if necessary',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Tire Pressure',
          placeholderValue: '',
          inputValue: '',
          order: 7,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Pressure ok',
              value: 'pressure_ok',
              uuid: '4c52db6f-deb3-41f4-9b00-417f18e936c2',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Needed fill up',
              value: 'needed_fill_up',
              uuid: '64868369-2cac-429b-a453-6d5f405c2c79',
              order: 1,
            },
          ],
        },
        {
          uuid: '9520858a-3755-4a1f-b91b-fbf6043a13ba',
          defaultValue: '',
          helperText: 'Record the state of the tire.',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Tire condition',
          placeholderValue: '',
          inputValue: '',
          order: 8,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Tire ok',
              value: 'tire_ok',
              uuid: '4c8431ef-5028-4b87-b4c3-1b9c302c65f1',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Punctured',
              value: 'punctured',
              uuid: '652c7bfb-f743-40bc-98bd-9fb054dd0617',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Worn out',
              value: 'worn_out',
              uuid: '5bd25c37-2844-421c-9ef1-4c80d96ba35f',
              order: 2,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Flat',
              value: 'flat',
              uuid: '079b2b18-7720-446d-bf26-e68803a4e9e1',
              order: 3,
            },
          ],
        },
      ],
    },
    {
      name: 'Back',
      isHidden: false,
      uuid: '503c4867-be5a-4c59-a501-7b6eb4284b4f',
      systemName: 'default_monthly_inspection_dc6aafbfedb4_back',
      parentFormUUID: '08eed68b-c7c9-4a33-9297-dc6aafbfedb4',
      version: '1.0.0',
      order: 7,
      formFields: [
        {
          uuid: 'a3337444-dd0e-4f06-8bcf-52e57d4d9093',
          defaultValue: '',
          helperText: 'Document the condition of the back license plate',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Back Plate Condition',
          placeholderValue: '',
          inputValue: '',
          order: 0,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Good condition',
              value: 'good_condition',
              uuid: '050110c2-aaeb-4a6a-8170-bee0990c20c4',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Damaged',
              value: 'damaged',
              uuid: 'c1e0fe21-bb84-44b6-a0dc-1db1c4287d8c',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Missing',
              value: 'missing',
              uuid: 'f143b407-71e1-4507-9033-ff4fc10d0f03',
              order: 2,
            },
          ],
        },
        {
          uuid: '3069837f-448a-41ae-81b1-7836e15cd219',
          defaultValue: '',
          helperText: 'Take a picture of the back plate to document it&amp;#39;s condition',
          isRequired: true,
          kind: ComponentTypes.SINGLE_IMAGE,
          label: 'Back plate picture',
          placeholderValue: '',
          inputValue: '',
          order: 1,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: '',
              value: '',
              uuid: '2926c48c-843e-4bd3-8ce8-eb5dc378ceaa',
              order: 0,
            },
          ],
        },
        {
          uuid: 'fd5ef6fe-be38-411c-881b-1351f1697241',
          defaultValue: '',
          helperText: 'Document the condition of the rear windows if applicable',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Window condition',
          placeholderValue: '',
          inputValue: '',
          order: 2,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Not applicable',
              value: 'not_applicable',
              uuid: '0d69c40b-1e01-4ddf-ab12-1eea0c123ef1',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Condition ok',
              value: 'condition_ok',
              uuid: '74e52b3e-2a22-4450-ae78-25fd83f7774c',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Cracked',
              value: 'cracked',
              uuid: '339af019-5b2b-4279-b0bc-6f49fdb6643b',
              order: 2,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Chipped',
              value: 'chipped',
              uuid: '03c6d9cd-9e21-4436-ad11-d91f3981668c',
              order: 3,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Shattered',
              value: 'shattered',
              uuid: 'f0810082-95e1-40b1-8091-024b2ee957fb',
              order: 4,
            },
          ],
        },
        {
          uuid: '3b656431-8b8f-4208-91e5-3b38165d7035',
          defaultValue: '',
          helperText: 'Document the condition of the outside handle',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Outside handle condition',
          placeholderValue: '',
          inputValue: '',
          order: 3,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Handle ok',
              value: 'handle_ok',
              uuid: '4218c276-9786-43ad-b507-a4925e483bd7',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Handle broken',
              value: 'handle_broken',
              uuid: '67c72ef5-40ee-446c-bc2b-fb6dd2c50eb2',
              order: 1,
            },
          ],
        },
        {
          uuid: 'b32c9f1f-4269-43a8-b52f-835a737654b9',
          defaultValue: '',
          helperText: 'Document the condition of the rear door inside handle',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Rear inside handle',
          placeholderValue: '',
          inputValue: '',
          order: 4,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Handle ok',
              value: 'handle_ok',
              uuid: '7d193882-47b2-4272-8985-a29bce83e41e',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Handle broken',
              value: 'handle_broken',
              uuid: '8bda5c23-b10a-4c55-b362-7c355c314acd',
              order: 1,
            },
          ],
        },
        {
          uuid: '961b4fb1-5b6f-4e3d-9fe1-1f9fbb6ac552',
          defaultValue: '',
          helperText: 'Document the condition of the wiring for the rear doors',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Door wiring',
          placeholderValue: '',
          inputValue: '',
          order: 5,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Both doors ok',
              value: 'both_doors_ok',
              uuid: 'e86d7231-385e-48bc-add5-689d53539d95',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Wiring needs replacing',
              value: 'wiring_needs_replacing',
              uuid: '657d03e5-4de0-42e4-be00-ca49e2c31904',
              order: 1,
            },
          ],
        },
        {
          uuid: '4b2f5a66-e48e-4174-b886-51a92f6783b9',
          defaultValue: '',
          helperText: 'Document if the spare tire is present',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Spare tire',
          placeholderValue: '',
          inputValue: '',
          order: 6,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Spare present',
              value: 'spare_present',
              uuid: '3e854244-e3f6-48f4-bab2-6efcf398a28f',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Spare missing',
              value: 'spare_missing',
              uuid: '0e00a0c7-d779-429f-8c3b-ba2413352bfc',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Spare damaged',
              value: 'spare_damaged',
              uuid: 'fdb95998-465e-41a5-8e31-71c9e6676f45',
              order: 2,
            },
          ],
        },
      ],
    },
    {
      name: 'Passenger side',
      isHidden: false,
      uuid: 'fa9599ef-b2ec-4abc-a9d6-7636947c65e7',
      systemName: 'default_monthly_inspection_dc6aafbfedb4_passenger_side',
      parentFormUUID: '08eed68b-c7c9-4a33-9297-dc6aafbfedb4',
      version: '1.0.0',
      order: 8,
      formFields: [
        {
          uuid: 'b13ab9a9-2d06-42a5-9543-bb728e6a9fbe',
          defaultValue: '',
          helperText: '',
          isRequired: true,
          kind: ComponentTypes.NUMBER,
          label: 'Rear tire inner tread',
          placeholderValue: '',
          inputValue: '',
          order: 0,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: '',
              value: '',
              uuid: '6b13d4f8-56f0-47f1-80a5-4ad429f9c569',
              order: 0,
            },
          ],
        },
        {
          uuid: '23e78d31-9848-4a26-a568-0ad9e63b7605',
          defaultValue: '',
          helperText: '',
          isRequired: true,
          kind: ComponentTypes.NUMBER,
          label: 'Rear tire middle tread',
          placeholderValue: '',
          inputValue: '',
          order: 1,
          formFieldOptions: [],
        },
        {
          uuid: '9cbcf5c9-9909-4647-8206-ca29bf98e39c',
          defaultValue: '',
          helperText: '',
          isRequired: true,
          kind: ComponentTypes.NUMBER,
          label: 'Rear tire outer tread',
          placeholderValue: '',
          inputValue: '',
          order: 2,
          formFieldOptions: [],
        },
        {
          uuid: '09f56d64-1349-4d06-a252-a4885be03df6',
          defaultValue: '',
          helperText: '',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Rear tire pressure',
          placeholderValue: '',
          inputValue: '',
          order: 3,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Pressure good',
              value: 'pressure_good',
              uuid: '00fe7af5-8ed2-4941-8291-89e08f5d893d',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Flat',
              value: 'flat',
              uuid: 'c0bebb04-ab08-4e6c-ab1e-9b4a55721d8e',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Low - needed filling',
              value: 'low_-_needed_filling',
              uuid: '842f6111-b3a8-432e-b8a6-bc005e4215cc',
              order: 2,
            },
          ],
        },
        {
          uuid: '2433f202-dd0d-4d9c-a069-58657472f20a',
          defaultValue: '',
          helperText: '',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'rear_tire_condition',
          placeholderValue: '',
          inputValue: '',
          order: 4,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Tire good',
              value: 'tire_good',
              uuid: '868f3ab1-571c-4dfc-8403-5ed038d211d4',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Punctured ',
              value: 'punctured_',
              uuid: '3148fdb7-a773-437f-9f7b-0c330dc6345f',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Worn out',
              value: 'worn_out',
              uuid: 'bd29376e-e102-40d2-87dc-cf710302f6d7',
              order: 2,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Flat',
              value: 'flat',
              uuid: 'df121e40-c2f2-4a3f-9abf-c7dbdb00a928',
              order: 3,
            },
          ],
        },
        {
          uuid: '06c5a370-7242-4631-bd6d-27577376f7e5',
          defaultValue: '',
          helperText: 'Document the condition of the sliding door latch',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Sliding door latch',
          placeholderValue: '',
          inputValue: '',
          order: 5,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Latch ok',
              value: 'latch_ok',
              uuid: '00007487-85db-40ac-95e4-a170ca11b0de',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Latch damaged / missing',
              value: 'latch_damaged_/_missing',
              uuid: '06af6bab-2480-4e28-9f5b-d0493a16891c',
              order: 1,
            },
          ],
        },
        {
          uuid: 'fcf39a99-6ec4-48fc-be48-a2067231311f',
          defaultValue: '',
          helperText: 'Document the condition of the handles on the sliding door',
          isRequired: true,
          kind: ComponentTypes.MULTISELECT,
          label: 'Sliding door handles',
          placeholderValue: '',
          inputValue: '',
          order: 6,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Both handles ok',
              value: 'both_handles_ok',
              uuid: '8672ae93-2f8d-42e6-87cc-d26addbefa8f',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Outer handle damaged',
              value: 'outer_handle_damaged',
              uuid: 'edf9c895-4aac-4cef-879b-a6293a9f4e54',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Inner handle damaged',
              value: 'inner_handle_damaged',
              uuid: '8eabad7c-018b-4231-9f24-64f276bf2e17',
              order: 2,
            },
          ],
        },
        {
          uuid: '984c137e-1b9b-4739-bfef-47a8a50ee51a',
          defaultValue: '',
          helperText: 'Document the condition of the sliding door alignment nut',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Sliding door alignment nut',
          placeholderValue: '',
          inputValue: '',
          order: 7,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Ok',
              value: 'ok',
              uuid: 'fca9b640-d423-4e89-9892-8538b3ef43ed',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Damaged / Missing',
              value: 'damaged_/_missing',
              uuid: '33751c70-e89e-4af9-af05-defbc1931918',
              order: 1,
            },
          ],
        },
        {
          uuid: '34f788c1-aa8f-4fac-b549-256a730bd497',
          defaultValue: '',
          helperText: 'Document the condition of the passenger side door check',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Passenger door check',
          placeholderValue: '',
          inputValue: '',
          order: 8,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Door check good',
              value: 'door_check_good',
              uuid: '8a9fadde-ffb3-4899-abcc-919c8f067988',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Door check damaged',
              value: 'door_check_damaged',
              uuid: 'a538798b-1725-4943-8e1e-e2b47bc4101a',
              order: 1,
            },
          ],
        },
        {
          uuid: 'c46533c4-a7fe-41cf-a927-f0117804028f',
          defaultValue: '',
          helperText: 'Document the condition of the passenger door window',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Passenger door window condition',
          placeholderValue: '',
          inputValue: '',
          order: 9,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Window ok',
              value: 'window_ok',
              uuid: '55d5147d-3de1-4735-a889-ee61d54eddd4',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Shattered',
              value: 'shattered',
              uuid: 'ebb133dd-e686-4a34-b1b1-68993681fa9a',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Cracked',
              value: 'cracked',
              uuid: '6d6278c0-f16b-45d6-b03b-ab1ceb71f9bc',
              order: 2,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Chipped',
              value: 'chipped',
              uuid: '392caf3c-e1a9-445b-8cc2-d1de58f81cec',
              order: 3,
            },
          ],
        },
        {
          uuid: 'a5aa0ee2-aa25-4bec-85c2-3d447c784d8a',
          defaultValue: '',
          helperText: '',
          isRequired: false,
          kind: ComponentTypes.NUMBER,
          label: 'Front tire inner tread',
          placeholderValue: '',
          inputValue: '',
          order: 10,
          formFieldOptions: [],
        },
        {
          uuid: '8e3e43a8-01a7-4aba-a6d7-79f109a212c8',
          defaultValue: '',
          helperText: '',
          isRequired: true,
          kind: ComponentTypes.NUMBER,
          label: 'Front tire middle tread',
          placeholderValue: '',
          inputValue: '',
          order: 11,
          formFieldOptions: [],
        },
        {
          uuid: '4d071027-6f87-4317-9e86-fb33ab206861',
          defaultValue: '',
          helperText: '',
          isRequired: true,
          kind: ComponentTypes.NUMBER,
          label: 'Front tire outer tread',
          placeholderValue: '',
          inputValue: '',
          order: 12,
          formFieldOptions: [],
        },
        {
          uuid: 'e2b5247d-eccc-415e-b1ac-3eb716ef0cfd',
          defaultValue: '',
          helperText: '',
          isRequired: true,
          kind: ComponentTypes.SINGLE_IMAGE,
          label: 'Front tire tread picture',
          placeholderValue: '',
          inputValue: '',
          order: 13,
          formFieldOptions: [],
        },
        {
          uuid: 'de74a72d-a3c2-4914-a2a7-304452d585de',
          defaultValue: '',
          helperText: '',
          isRequired: true,
          kind: ComponentTypes.RADIO,
          label: 'Fron tire pressure',
          placeholderValue: '',
          inputValue: '',
          order: 14,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Pressure good',
              value: 'pressure_good',
              uuid: '63533533-8f47-44eb-9d0b-9a46a46a508a',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Flat',
              value: 'flat',
              uuid: '452f1cb5-d8d6-408c-8322-0730ba296c89',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Low - needed filling',
              value: 'low_-_needed_filling',
              uuid: '48d2aa37-3e54-4130-a7d2-199c8b388385',
              order: 2,
            },
          ],
        },
        {
          uuid: '1aab3d40-56de-4b50-9d8f-485c9e9da47a',
          defaultValue: '',
          helperText: '',
          isRequired: false,
          kind: ComponentTypes.RADIO,
          label: 'Front tire condition',
          placeholderValue: '',
          inputValue: '',
          order: 15,
          formFieldOptions: [
            {
              linkedForm: '',
              isSelected: false,
              label: 'Tire good',
              value: 'tire_good',
              uuid: '7d896351-68ac-4809-8675-ae96f71a3c54',
              order: 0,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Flat',
              value: 'flat',
              uuid: 'b552c796-63a8-40ee-a850-76bd24ebacab',
              order: 1,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Punctured',
              value: 'punctured',
              uuid: '85c220cd-4501-4bcd-83f3-fd819408ee19',
              order: 2,
            },
            {
              linkedForm: '',
              isSelected: false,
              label: 'Worn out',
              value: 'worn_out',
              uuid: 'bca8e972-3b16-473f-9dfa-ed981c1c09c1',
              order: 3,
            },
          ],
        },
      ],
    },
  ],
};
